import type { Metadata } from "next"

import { pretendard, hahmlet, source } from "~/app/fonts"

import "@repo/ui/globals.css"
import "~/app/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} ${hahmlet.variable} ${source.variable}`}>
        {children}
      </body>
    </html >
  )
}
