name: Sync shadcn/ui v4 for Monorepo with Tailwind CSS v4

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * 1" # 매주 월요일 자정에 실행
  workflow_dispatch: # 수동 실행 가능
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (github.event.pull_request.head.ref == 'sync/shadcn-v4' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and prepare sync branch
        run: |
          # 기존 브랜치가 있는지 확인하고 생성
          if git ls-remote --heads origin sync/shadcn-v4 | grep -q sync/shadcn-v4; then
            echo "브랜치가 이미 존재합니다. 최신 main으로 재설정합니다."
            git checkout main
            git pull origin main
            git checkout -B sync/shadcn-v4
            git reset --hard main
          else
            echo "새로운 브랜치를 생성합니다."
            git checkout -b sync/shadcn-v4
          fi

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Clone shadcn/ui v4
        run: git clone --depth=1 https://github.com/shadcn-ui/ui.git tmp-shadcn-ui

      - name: Create required directories
        run: |
          mkdir -p packages/ui/src/components
          mkdir -p packages/ui/src/lib
          mkdir -p packages/ui/src/hooks
          mkdir -p packages/ui/src/styles

      - name: Sync monorepo template
        run: |
          echo "monorepo 템플릿에서 파일 동기화 중..."

          # 컴포넌트 동기화 (monorepo 템플릿)
          if [ -d tmp-shadcn-ui/templates/monorepo-next/packages/ui/src/components ]; then
            echo "✅ 템플릿에서 컴포넌트 복사 중..."
            rsync -av --delete tmp-shadcn-ui/templates/monorepo-next/packages/ui/src/components/ packages/ui/src/components/
          fi

          # 유틸리티 동기화 (monorepo 템플릿)
          if [ -d tmp-shadcn-ui/templates/monorepo-next/packages/ui/src/lib ]; then
            echo "✅ 템플릿에서 유틸리티 복사 중..."
            rsync -av --delete tmp-shadcn-ui/templates/monorepo-next/packages/ui/src/lib/ packages/ui/src/lib/
          fi

          # 훅 동기화 (monorepo 템플릿)
          if [ -d tmp-shadcn-ui/templates/monorepo-next/packages/ui/src/hooks ]; then
            echo "✅ 템플릿에서 훅 복사 중..."
            rsync -av --delete tmp-shadcn-ui/templates/monorepo-next/packages/ui/src/hooks/ packages/ui/src/hooks/
          fi

          # 스타일 동기화 (monorepo 템플릿)
          if [ -d tmp-shadcn-ui/templates/monorepo-next/packages/ui/src/styles ]; then
            echo "✅ 템플릿에서 스타일 복사 중..."
            rsync -av --delete tmp-shadcn-ui/templates/monorepo-next/packages/ui/src/styles/ packages/ui/src/styles/
          fi

      - name: Sync v4 app components
        run: |
          echo "v4 앱에서 추가 컴포넌트 동기화 중..."

          # v4 앱에서 추가 컴포넌트를 찾아서 추가
          if [ -d tmp-shadcn-ui/apps/v4/components ]; then
            echo "✅ v4 앱에서 컴포넌트 추가 중..."
            mkdir -p tmp-components
            rsync -av tmp-shadcn-ui/apps/v4/components/ tmp-components/

            # 이미 존재하는 컴포넌트와 중복되지 않는 항목만 복사
            rsync -av --ignore-existing tmp-components/ packages/ui/src/components/
            rm -rf tmp-components
          fi

      - name: Update components.json from template
        run: |
          if [ -f tmp-shadcn-ui/templates/monorepo-next/packages/ui/components.json ]; then
            echo "✅ components.json 템플릿에서 복사 중..."

            # components.json 템플릿 복사
            cp tmp-shadcn-ui/templates/monorepo-next/packages/ui/components.json packages/ui/

            # Tailwind CSS v4 설정 적용
            jq '.tailwind.config = ""' packages/ui/components.json > packages/ui/components.json.tmp
            mv packages/ui/components.json.tmp packages/ui/components.json
          fi

      - name: Update package.json dependencies
        run: |
          if [ -f tmp-shadcn-ui/templates/monorepo-next/packages/ui/package.json ]; then
            echo "✅ package.json 템플릿에서 의존성 업데이트 중..."

            SOURCE_DEPS=$(jq -c '.dependencies // {}' tmp-shadcn-ui/templates/monorepo-next/packages/ui/package.json)
            SOURCE_PEER_DEPS=$(jq -c '.peerDependencies // {}' tmp-shadcn-ui/templates/monorepo-next/packages/ui/package.json)

            # 현재 package.json 업데이트 - 의존성 병합 (오버라이드 없이)
            jq --argjson srcDeps "$SOURCE_DEPS" --argjson srcPeerDeps "$SOURCE_PEER_DEPS" '.dependencies += $srcDeps | .peerDependencies += $srcPeerDeps' packages/ui/package.json > packages/ui/package.json.tmp
            mv packages/ui/package.json.tmp packages/ui/package.json
          fi

      - name: Clean up temporary files
        run: rm -rf tmp-shadcn-ui

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            git add .
            git commit -m "chore: sync shadcn/ui v4 components for monorepo"
            git push -f origin sync/shadcn-v4
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          commit-message: "chore: sync shadcn/ui v4 components for monorepo"
          title: "chore: sync shadcn/ui v4 components for monorepo"
          body: |
            # shadcn/ui v4 컴포넌트 동기화

            이 PR은 shadcn/ui v4의 monorepo 템플릿에서 컴포넌트, 유틸리티, 훅, 스타일을 동기화합니다.

            ## 동기화된 항목
            - 컴포넌트 (`/src/components/`)
            - 유틸리티 (`/src/lib/`)
            - 훅 (`/src/hooks/`)
            - 스타일 (`/src/styles/`)
            - 의존성 (`package.json`)
            - 설정 (`components.json`)

            ## Tailwind CSS v4 호환성

            이 PR은 Tailwind CSS v4와 호환되도록 업데이트되었습니다.

            변경사항을 검토하고 필요한 경우 수정 후 머지해주세요.
          branch: "sync/shadcn-v4"
          base: "main"
          labels: "dependencies,ui,shadcn"
