name: Sync shadcn/ui v4 for Monorepo with Tailwind CSS v4

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' &&
       github.ref == 'refs/heads/main' &&
       contains(github.event.head_commit.message, 'Merge pull request') &&
       contains(github.event.head_commit.message, 'sync/shadcn-v4'))

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and prepare sync branch
        run: |
          git checkout -B sync/shadcn-v4-monorepo origin/main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Clone shadcn/ui v4
        run: git clone --depth=1 https://github.com/shadcn-ui/ui.git tmp-shadcn-ui

      - name: Copy components from shadcn/ui v4
        run: |
          echo "Creating directories..."
          mkdir -p packages/ui/src/{components,lib,hooks,styles}

          echo "Copying from known structure at tmp-shadcn-ui/apps/v4/registry/new-york-v4..."

          # Copy UI components
          if [ -d "tmp-shadcn-ui/apps/v4/registry/new-york-v4/ui" ]; then
            cp -rv tmp-shadcn-ui/apps/v4/registry/new-york-v4/ui/* packages/ui/src/components/
            echo "UI components copied successfully"
          else
            echo "Error: UI components directory not found at expected path"
            exit 1
          fi

          # Copy lib files
          if [ -d "tmp-shadcn-ui/apps/v4/registry/new-york-v4/lib" ]; then
            cp -rv tmp-shadcn-ui/apps/v4/registry/new-york-v4/lib/* packages/ui/src/lib/
            echo "Lib files copied successfully"
          else
            echo "Warning: Lib directory not found at expected path"
          fi

          # Copy hooks
          if [ -d "tmp-shadcn-ui/apps/v4/registry/new-york-v4/hooks" ]; then
            cp -rv tmp-shadcn-ui/apps/v4/registry/new-york-v4/hooks/* packages/ui/src/hooks/
            echo "Hooks copied successfully"
          else
            echo "Warning: Hooks directory not found at expected path"
          fi

          # Copy styles
          if [ -d "tmp-shadcn-ui/apps/v4/registry/new-york-v4/styles" ]; then
            cp -rv tmp-shadcn-ui/apps/v4/registry/new-york-v4/styles/* packages/ui/src/styles/
            echo "Styles copied successfully"
          else
            echo "Warning: Styles directory not found at expected path"
          fi

          echo "Checking destination directories..."
          ls -la packages/ui/src/components
          ls -la packages/ui/src/lib 2>/dev/null || echo "No lib files copied"
          ls -la packages/ui/src/hooks 2>/dev/null || echo "No hooks copied"
          ls -la packages/ui/src/styles 2>/dev/null || echo "No styles copied"

      - name: Clean up temporary files
        run: rm -rf tmp-shadcn-ui

      - name: Check for changes and push
        id: changes
        run: |
          git status
          # Check if there's anything to commit
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, committing..."
            git add .
            git commit -m "chore: sync shadcn/ui v4 components for monorepo"
            git push -f origin sync/shadcn-v4-monorepo
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync shadcn/ui v4 components for monorepo"
          title: "chore: sync shadcn/ui v4 components for monorepo"
          body: |
            # shadcn/ui v4 컴포넌트 동기화

            이 PR은 shadcn/ui v4의 monorepo 템플릿에서 컴포넌트, 유틸리티, 훅, 스타일을 동기화합니다.

            ## 동기화된 항목
            - 컴포넌트 (`/src/components/`)
            - 유틸리티 (`/src/lib/`)
            - 훅 (`/src/hooks/`)
            - 스타일 (`/src/styles/`)

            ## Tailwind CSS v4 호환성

            이 PR은 Tailwind CSS v4와 호환되도록 업데이트되었습니다.

            변경사항을 검토하고 필요한 경우 수정 후 머지해주세요.
          branch: sync/shadcn-v4-monorepo
          base: main
          labels: dependencies,ui,shadcn
          delete-branch: false
